# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf5fff0841ae3fe7450735d05aec3a7f45033fdd4a1d19c744cfdfcbb05a04f105d506ad3f0932225115937da56916b4c1ef534021b78d62c7f617eeb0aefc8

test:
  secret_key_base: 7d92636f4ec4a12b1a4af32866be759342b01a5230a45c82a24a7e486f57151895c1c1b26115e030bc067cd2d2dd124de89d7ea841c11ca4a0fb1d1410cacdc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
